### ISSUE TITLE
Repository not found on new Ubuntu 18.04

### ISSUE THREAD

**Issue by bandicootdancing** [poppabear8883/UNIT3D-INSTALLER#36]
Working on a second fresh install for this. Currently trying a fresh install of Ubuntu 18.04LTS from their website. After the installer finishes setting up UFW it fails at this line in the installer.
```git clone --single-branch --branch development https://github.com/HDInnovations/UNIT3D-HiFi.git /var/www/html```

``[ERROR] Cloning into '/var/www/html'...
                 remote: Repository not found.
                 fatal: repository 'https://github.com/HDInnovations/UNIT3D-HiFi.git/' not found``

**Comment by HDVinnie** [comment]
umm....you're using the wrong installer.

This repo/installer is for UNIT3D. 
https://github.com/poppabear8883/UNIT3D-INSTALLER
https://github.com/HDInnovations/UNIT3D

Seems your using https://github.com/HDInnovations/UNIT3D-HiFi-Installer which is a installer for a private project called UNIT3D-HiFi which is why you don't have access.
