### ISSUE TITLE
Error ./ubuntu.sh: line 42: php: command not found

### ISSUE THREAD

**Issue by Kongledyret** [poppabear8883/UNIT3D-INSTALLER#9]
Hi, 
I got this error: ./ubuntu.sh: line 42: php: command not found
Ubuntu 16.04

**Comment by poppabear8883** [comment]
Please re-run `sudo ./install.sh`

**Comment by Kongledyret** [comment]
Same issue

**Comment by poppabear8883** [comment]
Can you please provide the `full` output ?

**Comment by Kongledyret** [comment]
18.04 did the trick.

**Comment by poppabear8883** [comment]
Ok, I will comment on what I know about this error and close the issue.

This error normally occurs when the script was `unsuccessful` at installing `PHP` during the environment setup.

The code responsible for this is below:
```bash
if ! [ -x "$(command -v php)" ]; then
    echo -e "\n$Cyan Updating Packages ... $Color_Off"
    apt-get -qq update
    echo -e "$IGreen OK $Color_Off"

    echo -e "\n$Cyan Installing PHP ... $Color_Off"
    apt-get install -qq curl debconf-utils php-pear php7.2-curl php7.2-dev php7.2-gd php7.2-mbstring php7.2-zip php7.2-mysql php7.2-xml php7.2-fpm > /dev/null
    echo -e "$IGreen OK $Color_Off"
fi
```

Tested on:
```
Distributor ID: Ubuntu
Description:    Ubuntu 16.04 LTS
Release:        16.04
Codename:       xenial
```

Results of the environment setup:
![image](https://user-images.githubusercontent.com/7263458/43861836-085ea160-9b26-11e8-8122-2535934bec0c.png)

**If yours does not look like this then likely something went wrong**

Normally the solution to this issue is to simply `re-run the install.sh`. 

Otherwise you have a couple options:

1. Run the below command manually 
```bash
sudo add-apt-repository -y ppa:ondrej/php && sudo apt-get update && sudo apt-get install -y curl debconf-utils php-pear php7.2-curl php7.2-dev php7.2-gd php7.2-mbstring php7.2-zip php7.2-mysql php7.2-xml php7.2-fpm
```
**Then re-run the installer**

2. Reinstall the OS and try again ... **(never had to do this personally)**

In the future we hope to improve in this area.

**Comment by poppabear8883** [comment]
Ref commit: https://github.com/ServNX/UNIT3D-INSTALLER/commit/c38a730d3598dd6bb984c7193fb8861c523b9121
